### PR TITLE
Feature/Search

### PR DESCRIPTION
**Pull request by mattrabe**
Re #5 

- Initial interface and functionality
- Could use debouncing on the input
- magnifying lens graphic sourced from https://www.iconfinder.com/icons/6586131/find_glass_magnifier_search_seo_icon
- 🚧  ❗️ I think this can result in data loss - somewhere in CollectionList there must be something that saves to the collections. Should be refactored so that CollectionList is just a "dumb" presentational component which only outputs the array passed to it. @gilgold ?
- I also recommend adding linting to the project, to avoid the numerous whitespace & formatting issues that will arise as others contribute to the project. This PR is rather "noisy" because my IDE cleaned up a lot of whitespace issues automatically...

Feel free to comment/request changes/make changes/all that, or just completely reject this. I found an hour to play around with this today so I decided to take on the Search feature and had fun doing so!

### CODE REVIEW

**Comment by gilgold** [comment]
Hey @mattrabe thank you for the PR! 
I like your changes but I only have 1 concern from the UI part - the 2 textboxes (add and search) are a bit confusing, maybe hide the search textbox and instead have just a magnifying glass icon next to the "new window" switch, clicking it would reveal the search box (scroll down effect?).
Also, Tabox uses [React Icons](https://react-icons.github.io/react-icons/) so maybe get an icon from there instead? 

I can do the refactoring of CollectionList in a future ticket, for now it seems ok-ish.

Thank you again!

**Comment by mattrabe** [comment]
Thanks for the feedback @gilgold . I can go for that UI change next chance I get. If it takes me too long to get to it, feel free to take over. Also 👍 on React Icons.

I thought I saw my list of collections permanently get smaller while testing the search, which made me think CollectionList was running an automatic sync or something similar which was storing the smaller search-filtered list. I could be wrong. Luckily the "Restore from" feature in the gear icon saved me.

**Comment by gilgold** [comment]
Hmm I have heard from some people that all their collections disappeared but it was just a few cases and I thought it had to do with syncing - loading an empty list of collections from Google Drive. 
I will have to dig deeper into that

**Comment by gilgold** [comment]
I added search as a built in option to the "add collection" text box, now it will also do a search. thanks for your work though! I ended up using some parts of this PR 😄

**Pull request closed without merging**
